export const distantBuildings = [
  { id: 'distant-1', left: -2, width: 7, height: 42, roof: 'antenna' },
  { id: 'distant-2', left: 4, width: 6, height: 53, roof: 'flat' },
  { id: 'distant-3', left: 9, width: 8, height: 38, roof: 'stepped' },
  { id: 'distant-4', left: 15, width: 5, height: 59, roof: 'spire' },
  { id: 'distant-5', left: 19, width: 7, height: 46, roof: 'flat' },
  { id: 'distant-6', left: 25, width: 6, height: 55, roof: 'antenna' },
  { id: 'distant-7', left: 30, width: 8, height: 41, roof: 'stepped' },
  { id: 'distant-8', left: 37, width: 5, height: 63, roof: 'spire' },
  { id: 'distant-9', left: 41, width: 7, height: 49, roof: 'flat' },
  { id: 'distant-10', left: 47, width: 6, height: 57, roof: 'antenna' },
  { id: 'distant-11', left: 52, width: 8, height: 44, roof: 'stepped' },
  { id: 'distant-12', left: 59, width: 5, height: 65, roof: 'spire' },
  { id: 'distant-13', left: 63, width: 8, height: 50, roof: 'flat' },
  { id: 'distant-14', left: 70, width: 6, height: 59, roof: 'crown' },
  { id: 'distant-15', left: 75, width: 8, height: 43, roof: 'stepped' },
  { id: 'distant-16', left: 82, width: 5, height: 56, roof: 'spire' },
  { id: 'distant-17', left: 86, width: 7, height: 47, roof: 'flat' },
  { id: 'distant-18', left: 92, width: 6, height: 61, roof: 'antenna' },
  { id: 'distant-19', left: 97, width: 7, height: 40, roof: 'sloped' },
];

export const foregroundBuildings = [
  { id: 'ace-chemicals', left: -4, width: 17, height: 43, roof: 'stepped', light: 'warm' },
  { id: 'gotham-gazette', left: 10, width: 13, height: 58, roof: 'antenna', light: 'cool' },
  { id: 'monarch-theatre', left: 21, width: 17, height: 37, roof: 'flat', light: 'warm' },
  { id: 'wayne-tower', left: 35, width: 15, height: 68, roof: 'spire', light: 'warm' },
  { id: 'gotham-central', left: 48, width: 16, height: 49, roof: 'stepped', light: 'cool' },
  { id: 'old-gotham-bank', left: 62, width: 14, height: 61, roof: 'crown', light: 'warm' },
  { id: 'diamond-exchange', left: 74, width: 16, height: 42, roof: 'antenna', light: 'cool' },
  { id: 'gotham-harbour', left: 87, width: 17, height: 53, roof: 'sloped', light: 'warm' },
];
